services:
  ollama-generator:
    environment:
      - OLLAMA_DEBUG=true
  ollama-embedder:
    environment:
      - OLLAMA_DEBUG=true
  search:
    build:
      target: debug
    environment:
      - GIN_DEBUG=true
    ports:
      - "40000:40000"
  auth:
    command: start-dev

