services:
  ollama-generator:
    environment:
      - OLLAMA_DEBUG=true
  ollama-embedder:
    environment:
      - OLLAMA_DEBUG=true
  front:
    build:
      context: ./front
      target: debug
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
  search_service:
    build:
      target: debug
    environment:
      - GIN_DEBUG=true
    ports:
      - "40000:40000"
  search_database:
    # Inherits all settings from docker-compose.yml
  resource_service:
    build:
      target: debug
    environment:
      - GIN_DEBUG=true
    ports:
      - "40001:40001"
  resource_database:
    # Inherits all settings from docker-compose.yml
  auth_database:
    # Inherits all settings from docker-compose.yml
  auth:
    command: start-dev
    depends_on:
      mailhog:
        condition: service_started

  mailhog:
    image: mailhog/mailhog
    hostname: mailhog
    platform: linux/amd64
    restart: always
    ports:
      - 1025:1025  # SMTP port
      - 8025:8025  # Web UI port
    networks:
      webservices:
        aliases:
          - mailhog


