services:
  ollama-generator:
    environment:
      - OLLAMA_DEBUG=true
  ollama-embedder:
    environment:
      - OLLAMA_DEBUG=true
  front:
    build:
      context: ./front
      target: debug
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
  search:
    build:
      target: debug
    environment:
      - GIN_DEBUG=true
    ports:
      - "40000:40000"
  auth:
    command: start-dev

