services:
  front:
    build: ./front
    container_name: front
    ports:
      - "80:80"
    depends_on:
      search:
        condition: service_started
    networks:
      webservices:
        aliases:
          - front
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./front/Dockerfile
  search:
    build: ./search
    container_name: search
    ports:
      - "8080:8080"
    volumes:
      - ./search/.data:/{$GOPATH}/pkg/mod
    depends_on:
      ollama-embedder:
        condition: service_started
      ollama-generator:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      webservices:
        aliases:
          - search.deltanotes.orb.local
          - search
    develop:
      watch:
        - action: sync
          path: ./search
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./search/Dockerfile

  ollama-generator:
    image: ollama/ollama
    container_name: ollama-generator
    hostname: ollama-generator
    ports:
      - "11434:11434"
    volumes:
      - ./generator/.data:/root/.ollama
      - ./generator/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    restart: unless-stopped
    networks:
      webservices:
        aliases:
          - ollama-generator
    develop:
      watch:
        - action: sync
          path: ./generator
          target: /app
          ignore:
            - .data/
        - action: rebuild
          path: ./generator/Dockerfile

  ollama-embedder:
    image: ollama/ollama
    container_name: ollama-embedder
    hostname: ollama-embedder
    ports:
      - "11435:11434"
    volumes:
      - ./embedder/.data:/root/.ollama
      - ./embedder/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    restart: unless-stopped
    networks:
      webservices:
        aliases:
          - ollama-embedder
    develop:
      watch:
        - action: sync
          path: ./embedder
          target: /app
          ignore:
            - .data/
        - action: rebuild
          path: ./embedder/Dockerfile

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    hostname: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres/.data:/var/lib/postgresql/.data
      - ./postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      webservices:
        aliases:
          - postgres

networks:
  webservices:
    driver: bridge
