version: '3'

tasks:
  run-debug:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.debug.yml up --build -d
    silent: true
  run-prod:
    cmds:
      - docker compose -f docker-compose.yml up --build -d
    silent: true
  recreate-frontend:
    cmds:
      - docker compose up --force-recreate --no-deps front -d --build
    silent: true
  run-frontend-local:
    cmds:
      - cd front && npm run dev
  recreate-backend-debug:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.debug.yml up -force-recreate --no-deps search --build -d
    silent: true
  recreate-backend-prod:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml up -force-recreate --no-deps search --build -d
    silent: true
  down-all-delete-search_db:
    cmds:
      - docker compose down
      - rm -r ./search_database/.data
  down-all:
    cmd: docker compose down