// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckResourceOwnership(ctx context.Context, arg CheckResourceOwnershipParams) (bool, error)
	CountResourcesByOwner(ctx context.Context, ownerID pgtype.UUID) (int64, error)
	CountResourcesByStatus(ctx context.Context, status ResourceStatus) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Events, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resources, error)
	DeleteUsersResource(ctx context.Context, arg DeleteUsersResourceParams) error
	GetNotSentEvents(ctx context.Context, arg GetNotSentEventsParams) ([]Events, error)
	GetResources(ctx context.Context, arg GetResourcesParams) ([]Resources, error)
	GetResourcesByOwnerID(ctx context.Context, arg GetResourcesByOwnerIDParams) ([]Resources, error)
	GetResourcesByStatus(ctx context.Context, status ResourceStatus) ([]Resources, error)
	GetResourcesByType(ctx context.Context, type_ ResourceType) ([]Resources, error)
	GetResourcesCount(ctx context.Context, arg GetResourcesCountParams) (int64, error)
	GetResourcesWithFilter(ctx context.Context, arg GetResourcesWithFilterParams) ([]Resources, error)
	GetUsersResourceByID(ctx context.Context, arg GetUsersResourceByIDParams) (Resources, error)
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resources, error)
	UpdateUsersResource(ctx context.Context, arg UpdateUsersResourceParams) (Resources, error)
}

var _ Querier = (*Queries)(nil)
