CREATE EXTENSION vector;

CREATE TABLE IF NOT EXISTS chunks(
   id SERIAL PRIMARY KEY,
   data text NOT NULL
);

CREATE TABLE IF NOT EXISTS embedding(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    embedding public.vector(1536) NOT NULL,
    chunk_id bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT embeddings_chunks_embedding FOREIGN KEY (chunk_id) REFERENCES chunks (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);