production:
  server:
    host: "0.0.0.0"
    port: "8080"
    read_timeout: "5s"
    read_header_timeout: "2s"
    write_timeout: "500s"
    idle_timeout: "300s"
    max_header_bytes: 1048576
    shutdown_timeout: "10s"
  
  database:
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: "30m"
    conn_max_idle_time: "5m"
  
  logger:
    level: "error"
  
  kafka:
    producer:
      required_acks: -1
      retry_max: 1
      compression_type: "none"
    consumer:
      auto_offset_reset: "latest"
    topics:
      resource: "resource"
  
  outbox:
    interval: "30s"
    batch_size: 100
    max_retries: 3
    retry_delay: "5s"

debug:
  server:
    host: "localhost"
    port: "8080"
    read_timeout: "30s"
    read_header_timeout: "5s"
    write_timeout: "30s"
    idle_timeout: "30s"
    max_header_bytes: 1048576
    shutdown_timeout: "5s"
  
  database:
    max_open_conns: 5
    max_idle_conns: 2
    conn_max_lifetime: "30m"
    conn_max_idle_time: "5m"
  
  logger:
    level: "debug"
  
  kafka:
    producer:
      required_acks: -1
      retry_max: 1
      compression_type: "none"
    consumer:
      auto_offset_reset: "latest"
    topics:
      resource: "resource"
  
  outbox:
    interval: "10s"
    batch_size: 10
    max_retries: 1
    retry_delay: "2s"