// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Topic     string           `json:"topic"`
	Payload   []byte           `json:"payload"`
	Sent      bool             `json:"sent"`
	EventTime pgtype.Timestamp `json:"event_time"`
}
